services:
  e4-portal:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    image: e4-portal:latest
    container_name: e4-portal
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "7001:3000"
    environment:
      NODE_OPTIONS: "--dns-result-order=ipv4first"
      NETGSM_USERCODE: ${NETGSM_USERCODE}
      NETGSM_PASSWORD: ${NETGSM_PASSWORD}
      NETGSM_MSGHEADER: ${NETGSM_MSGHEADER}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_WHATSAPP_NUMBER: ${TWILIO_WHATSAPP_NUMBER}
      TWILIO_CONTENT_SID: ${TWILIO_CONTENT_SID}
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: npm_net
